DROP DATABASE IF EXISTS STUDENT_MANAGEMENT;
CREATE DATABASE STUDENT_MANAGEMENT; 
USE STUDENT_MANAGEMENT;
CREATE TABLE STUDENT (
ID INT,
`NAME` VARCHAR(25),
AGE INT,
COUNTRY VARCHAR(50),
PRIMARY KEY (ID));